### ISSUE TITLE
您好，能回复下吗

### ISSUE THREAD

**Issue by qindeer** [Jamie-Cui/jamie-cui.github.io#2]
您好，https://github.com/Littlegaga666/Secure-Two-party-K-means是您编写的吗？如果是，我想知道您在Secure-Two-party-K-means中只编写了一个框架吗？您的k-means在安全方面体现在哪个地方？另外，如何进行安全计算您有编写吗？

**Comment by Jamie-Cui** [comment]
> 您好，[https://github.com/Littlegaga666/Secure-Two-party-K-means是您编写的吗？如果是，我想知道您在Secure-Two-party-K-means中只编写了一个框架吗？您的k-means在安全方面体现在哪个地方？另外，如何进行安全计算您有编写吗？](https://github.com/Littlegaga666/Secure-Two-party-K-means%E6%98%AF%E6%82%A8%E7%BC%96%E5%86%99%E7%9A%84%E5%90%97%EF%BC%9F%E5%A6%82%E6%9E%9C%E6%98%AF%EF%BC%8C%E6%88%91%E6%83%B3%E7%9F%A5%E9%81%93%E6%82%A8%E5%9C%A8Secure-Two-party-K-means%E4%B8%AD%E5%8F%AA%E7%BC%96%E5%86%99%E4%BA%86%E4%B8%80%E4%B8%AA%E6%A1%86%E6%9E%B6%E5%90%97%EF%BC%9F%E6%82%A8%E7%9A%84k-means%E5%9C%A8%E5%AE%89%E5%85%A8%E6%96%B9%E9%9D%A2%E4%BD%93%E7%8E%B0%E5%9C%A8%E5%93%AA%E4%B8%AA%E5%9C%B0%E6%96%B9%EF%BC%9F%E5%8F%A6%E5%A4%96%EF%BC%8C%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E5%AE%89%E5%85%A8%E8%AE%A1%E7%AE%97%E6%82%A8%E6%9C%89%E7%BC%96%E5%86%99%E5%90%97%EF%BC%9F)

你列举的这个方案应该来自于论文：2007 CCS, Secure Two-Party k-Means Clustering, [eprint](http://web.cs.ucla.edu/~rafail/PUBLIC/87.pdf)，最新的 k-means 方案可参考今年 PETS 上的论文：Practical Privacy-Preserving K-means Clustering, [eprint](https://eprint.iacr.org/2019/1158)； Github 库: https://github.com/osu-crypto/secure-kmean-clustering
